import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '< welcome to paps dot dev />',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Jockey+One&family=Pathway+Gothic+One&display=swap');
        </style>
        <Header />
        {children}
      </body>
    </html>
  )
}
